### ISSUE TITLE
Mensa Südpark fehlt

### ISSUE THREAD

**Issue by AyAnniix248** [PhilPinsdorf/FhAachenMensaBot#69]
🥲

**Comment by Th3Ph4nt0m** [comment]
Die Mensen 'Südpark' und 'KMAC' werden von OpenMensa.org noch nicht bereitgestellt. Eine PR im entsprechenden Parser ist offen: https://github.com/mswart/openmensa-parsers/pull/148

Sobald ich von dort mehr weiß, mache ich hier eine PR auf ✌️

**Comment by PhilPinsdorf** [comment]
Ich parse inzwischen die Mensen selber und habe so die Mensa Südpark sowie alle anderen fehlenden Aachener Mensen zum Bot hinzugefügt. Die OpenMensaApi hatte einige Fehler, die nicht behoben wurden, weswegen das die letzte Möglichkeit war.
Unter anderem wurde auch die Mensa Academica als dauerhaft geschlossen angezeigt.

Mensa Südpark ist auswählbar mit /canteen
